name: API Client Generation
on:
  push:
    branches:
      - QTVY-111-swaggerhub # 특정 브랜치 지정
    paths:
      - 'src/api/generated/swagger.json' # 특정 경로의 파일 변경 시에만 트리거

jobs:
  generate-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Git 쓰기 권한 명시적 부여
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 전체 히스토리 체크아웃
          ref: ${{ github.head_ref }} # 현재 브랜치 명시

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Generate API Client
        run: pnpm generate-api

      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout ${{ github.ref_name }}  # 현재 브랜치로 명시적 체크아웃
          git add src/api/generated
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update API client"
          git push origin ${{ github.ref_name }}  # 현재 브랜치에 푸시
