name: API Client Generation
on:
  push:
    paths:
      - 'src/api/generated/swagger.json'

jobs:
  generate-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Git 쓰기 권한 명시적 부여
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 전체 히스토리 체크아웃

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Node.js 버전 명시

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Generate API Client
        run: pnpm generate:api

      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add src/api/generated
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update API client"
          git push
